export type ArchiveCategory = 'sites' | 'commerce' | 'apps' | 'tools' | 'experiments';

export interface ArchiveProject {
  repo: string;
  title: string;
  category: ArchiveCategory;
  kind: string;
  stack: string[];
  siteUrl?: string;
  siteLabel?: string;
  githubUrl?: string;
}

export const ARCHIVE_FILTERS: { value: 'all' | ArchiveCategory; label: string }[] = [
  { value: 'all', label: 'ALL' },
  { value: 'sites', label: 'SITES' },
  { value: 'commerce', label: 'COMMERCE' },
  { value: 'apps', label: 'APPS' },
  { value: 'tools', label: 'TOOLS' },
  { value: 'experiments', label: 'EXPERIMENTS' },
];

export const ARCHIVE_PROJECTS: ArchiveProject[] = [
  {
    repo: 'reformerpilatesmalta.com',
    title: 'Reformer Pilates Malta',
    category: 'sites',
    kind: 'Fitness booking platform',
    stack: ['Next.js', 'TypeScript', 'Firebase'],
    siteUrl: 'https://reformerpilatesmalta.com',
  },
  {
    repo: 'omeryigitler.com',
    title: 'Ömer Yiğitler',
    category: 'sites',
    kind: 'Studio portfolio system',
    stack: ['React', 'Vite', 'TypeScript', 'Tailwind'],
    siteUrl: 'https://omeryigitler.com',
    githubUrl: 'https://github.com/omeryigitler/omeryigitler.com',
  },
  {
    repo: 'bugunneyiyelim.com',
    title: 'Bugün Ne Yiyelim',
    category: 'apps',
    kind: 'Food discovery app',
    stack: ['Web App', 'Responsive UI', 'Vercel'],
    siteUrl: 'https://bugunneyiyelim.com',
  },
  {
    repo: 'ramazanda-malta.omeryigitler.com',
    title: 'Ramazanda Malta',
    category: 'apps',
    kind: 'Ramadan utility app',
    stack: ['Web App', 'Responsive UI', 'Vercel'],
    siteUrl: 'https://ramazanda-malta.omeryigitler.com',
  },
  {
    repo: 'atelier-couture-belgium',
    title: 'Atelier Couture Belgium',
    category: 'sites',
    kind: 'Fashion / couture website',
    stack: ['React', 'TypeScript', 'Vercel'],
    siteUrl: 'https://atelier-couture-belgium.vercel.app',
    siteLabel: 'VERCEL / ATELIER COUTURE',
  },
  {
    repo: 'dawlstudio.com',
    title: 'Dawl Studio',
    category: 'sites',
    kind: 'Creative studio commerce platform',
    stack: ['React', 'Vite', 'Supabase', 'Stripe'],
    siteUrl: 'https://dawlstudio.com',
  },
  {
    repo: 'builtwithseyhan.com',
    title: 'Built With Seyhan',
    category: 'sites',
    kind: 'Fitness coaching platform',
    stack: ['Next.js', 'TypeScript', 'Supabase', 'Tailwind'],
    siteUrl: 'https://builtwithseyhan.com',
  },
  {
    repo: 'yasemin-ozgan',
    title: 'Elena Moreau',
    category: 'sites',
    kind: 'Luxury real estate website',
    stack: ['React', 'TypeScript', 'Motion', 'Vercel'],
    siteUrl: 'https://elena-real-estate.vercel.app',
  },
  {
    repo: 'verdant-nyc---four-seasons-landscapes',
    title: 'Verdant NYC — Four Seasons Landscapes',
    category: 'sites',
    kind: 'Landscape studio website',
    stack: ['React', 'Responsive UI', 'Vercel'],
    siteUrl: 'https://verdant-nyc-four-seasons-landscapes.vercel.app',
    siteLabel: 'VERCEL / VERDANT NYC',
  },
  {
    repo: 'the-maltese-bean',
    title: 'The Maltese Bean',
    category: 'sites',
    kind: 'Hospitality / coffee website',
    stack: ['React', 'Responsive UI', 'Vercel'],
    siteUrl: 'https://the-maltese-bean.vercel.app',
    siteLabel: 'VERCEL / THE MALTESE BEAN',
  },
  {
    repo: 'module-page-v1',
    title: 'Module Page V1',
    category: 'tools',
    kind: 'SaaS module builder',
    stack: ['React', 'Vite', 'TypeScript', 'Supabase'],
    siteUrl: 'https://module-page-v1.vercel.app',
    siteLabel: 'VERCEL / MODULE PAGE',
  },
  {
    repo: 'core-engine-admin-panel',
    title: 'Core Engine Admin Panel',
    category: 'tools',
    kind: 'Admin / operations dashboard',
    stack: ['React', 'Vite', 'TypeScript', 'Recharts'],
    siteUrl: 'https://core-engine-admin-panel.vercel.app',
    siteLabel: 'VERCEL / CORE ENGINE',
  },
  {
    repo: 'parfum',
    title: 'Parfum',
    category: 'commerce',
    kind: 'Fragrance e-commerce',
    stack: ['React', 'Commerce UI', 'Vercel'],
    siteUrl: 'https://parfum-eta.vercel.app',
  },
  {
    repo: 'mybabyshire.com',
    title: 'MyBabyShire',
    category: 'commerce',
    kind: 'Baby e-commerce platform',
    stack: ['React', 'Vite', 'Prisma', 'Express'],
    siteUrl: 'https://mybabyshire.com',
  },
  {
    repo: 'full-stack',
    title: 'Full Stack',
    category: 'tools',
    kind: 'Full-stack development prototype',
    stack: ['Frontend', 'Backend', 'API'],
  },
  {
    repo: 'finance-agent-browser',
    title: 'Finance Agent Browser',
    category: 'tools',
    kind: 'Finance intelligence dashboard',
    stack: ['Python', 'FastAPI', 'Neon', 'Vercel'],
  },
  {
    repo: 'olinkbu.com',
    title: 'Olinkbu',
    category: 'apps',
    kind: 'Link / profile web app',
    stack: ['Web App', 'Responsive UI', 'Vercel'],
    siteUrl: 'https://olinkbu.com',
  },
  {
    repo: 'date.omeryigitler.com',
    title: 'Date',
    category: 'apps',
    kind: 'Date utility app',
    stack: ['Web App', 'Interaction', 'Vercel'],
    siteUrl: 'https://date.omeryigitler.com',
  },
  {
    repo: 'GymApp',
    title: 'Gym App',
    category: 'apps',
    kind: 'Workout tracking product',
    stack: ['Web App', 'TypeScript', 'Vercel'],
  },
  {
    repo: 'berfinakbas.com',
    title: 'Berfin Akbaş',
    category: 'sites',
    kind: 'Personal portfolio website',
    stack: ['React', 'Interaction', 'Vercel'],
    siteUrl: 'https://berfinakbas-com.vercel.app',
    githubUrl: 'https://github.com/omeryigitler/berfinakbas.com',
  },
  {
    repo: 'nailstudio',
    title: 'Nail Studio',
    category: 'commerce',
    kind: 'Beauty / booking commerce',
    stack: ['React', 'Commerce UI', 'Vercel'],
    siteUrl: 'https://nailstudio-gamma.vercel.app',
  },
  {
    repo: 'Dashboard',
    title: 'Dashboard',
    category: 'tools',
    kind: 'Content / operations dashboard',
    stack: ['React', 'Vite', 'Express', 'TypeScript'],
    siteUrl: 'https://dashboard-dasboard.vercel.app',
    siteLabel: 'VERCEL / DASHBOARD',
    githubUrl: 'https://github.com/omeryigitler/Dashboard',
  },
  {
    repo: 'kedi',
    title: 'Kedi',
    category: 'experiments',
    kind: 'Creative interaction experiment',
    stack: ['Interaction', 'Motion', 'Frontend'],
    githubUrl: 'https://github.com/omeryigitler/kedi',
  },
  {
    repo: 'cafe',
    title: 'Cafe',
    category: 'commerce',
    kind: 'Hospitality / commerce experience',
    stack: ['React', 'Motion', 'Vercel'],
    siteUrl: 'https://cafe-o-co.vercel.app',
    siteLabel: 'VERCEL / CAFE',
    githubUrl: 'https://github.com/omeryigitler/cafe',
  },
  {
    repo: 'xxl-cafe-o-co.',
    title: 'XXL Cafe & Co.',
    category: 'commerce',
    kind: 'Coffee commerce website',
    stack: ['React', 'Commerce UI', 'Vercel'],
    siteUrl: 'https://xxl-cafe-o-co.vercel.app',
    githubUrl: 'https://github.com/omeryigitler/xxl-cafe-o-co.',
  },
  {
    repo: 'startpage',
    title: 'Startpage',
    category: 'sites',
    kind: 'Personal command dashboard',
    stack: ['Next.js', 'TypeScript', 'Neon', 'NextAuth'],
    siteUrl: 'https://start.omeryigitler.com',
    siteLabel: 'START.OMERYIGITLER.COM',
    githubUrl: 'https://github.com/omeryigitler/startpage',
  },
  {
    repo: 'Japanese-Bakery',
    title: 'Japanese Bakery',
    category: 'commerce',
    kind: 'Editorial food e-commerce',
    stack: ['React', 'Interaction', 'Vercel'],
    siteUrl: 'https://japanese-bakery.vercel.app',
    githubUrl: 'https://github.com/omeryigitler/Japanese-Bakery',
  },
  {
    repo: 'Architecture-eCommerce-3D',
    title: 'Architecture eCommerce 3D',
    category: 'commerce',
    kind: '3D product commerce experience',
    stack: ['React', '3D Web', 'Interaction', 'Vercel'],
    siteUrl: 'https://architecture-e-commerce-3d.vercel.app',
    githubUrl: 'https://github.com/omeryigitler/Architecture-eCommerce-3D',
  },
  {
    repo: '-Property-Management',
    title: 'Property Management',
    category: 'apps',
    kind: 'Property management app',
    stack: ['Application UI', 'Data', 'Frontend'],
    githubUrl: 'https://github.com/omeryigitler/-Property-Management',
  },
  {
    repo: 'mybabyshire-archive',
    title: 'MyBabyShire Archive',
    category: 'commerce',
    kind: 'Legacy baby commerce experience',
    stack: ['React', 'Commerce UI', 'Vercel'],
    siteUrl: 'https://mybabyshire-archive.vercel.app',
  },
  {
    repo: 'reformer',
    title: 'Reformer',
    category: 'commerce',
    kind: 'Wellness booking experience',
    stack: ['React', 'Booking UI', 'Vercel'],
    siteUrl: 'https://reformer-beta.vercel.app',
    githubUrl: 'https://github.com/omeryigitler/reformer',
  },
  {
    repo: 'muhasebe',
    title: 'Muhasebe',
    category: 'apps',
    kind: 'Accounting / calculator website',
    stack: ['React', 'Vite', 'GSAP', 'Tailwind'],
    siteUrl: 'https://muhasebe-delta-virid.vercel.app',
    siteLabel: 'VERCEL / MUHASEBE',
    githubUrl: 'https://github.com/omeryigitler/muhasebe',
  },
  {
    repo: 'Portfolio',
    title: 'Portfolio',
    category: 'sites',
    kind: 'Portfolio design system',
    stack: ['React', 'TypeScript', 'Vite', 'GSAP'],
    githubUrl: 'https://github.com/omeryigitler/Portfolio',
  },
];

export const ARCHIVE_COUNT = ARCHIVE_PROJECTS.length;
